services:
  ollama:
    build: ./ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./data/ollama:/root/.ollama
    restart: unless-stopped

  api:
    build: .
    container_name: api
    command: python -m src.api.app
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    restart: unless-stopped

  agent: