services:
  ollama:
    build: ./ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./data/ollama:/root/.ollama
    restart: unless-stopped

  api:
    build: .
    container_name: api
    command: python -m app.src.api.app
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    restart: unless-stopped

  agent:
    build: .
    container_name: agent
    command: python -m app.src.ui.grad
    ports:
      - "7860:7860"
    depends_on:
      - api
    restart: unless-stopped


networks:
  data_sus_network:
    driver: bridge

volumes:
  ollama_data:
    driver: local