[project]
name = "api"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "db-sqlite3>=0.0.1",
    "fastapi>=0.119.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/api"] 
